parent: $LVSR/exp/wsj/configs/wsj_paper6.yaml
regularization:
    max_norm: 0.
    norm_penalty: 10.
data:
    batch_size: 10

initialization:
    /recognizer:
        initial_states_init:
            !!python/object/apply:blocks.initialization.IsotropicGaussian [0.01]

